name: NAFNetV3-baseline-enc3_ch_mid_32_mid_12_shuffle1_2_width_32
model_type: ImageRestorationModel
scale: 1
num_gpu: 2
manual_seed: 10
datasets:
  train:
    name: SIDD
    type: PairedImageRawDataset
    dataroot_gt: /data1/SIDD_raw/train/gt_raw_crops_lmdb
    dataroot_lq: /data1/SIDD_raw/train/lq_raw_crops_lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
    gt_size: 256
    use_flip: false
    use_rot: false
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: null
    phase: train
    scale: 1
  val:
    name: SIDD_val
    type: PairedImageRawDataset
    dataroot_gt: /data1/SIDD_raw/valid/valid_gt_raw_crops
    dataroot_lq: /data1/SIDD_raw/valid/valid_lq_raw_crops
    io_backend:
      type: disk
    phase: val
    scale: 1
network_g:
  type: NAFNetV3
  input_shuffle: 2
  shuffle: 2
  width: 32
  ch_mid: 32
  enc_blk_nums:
  - 2
  - 2
  - 2
  middle_blk_num: 12
  dec_blk_nums:
  - 2
  - 2
  - 2
  ending_blk_type: 0
  middle_blk_type: 0
  sca: true
path:
  pretrain_network_g: null
  strict_load_g: true
  resume_state: null
  root: /home/jaewon/AIISP2024
  experiments_root: /home/jaewon/AIISP2024/experiments/NAFNetV3-baseline-enc3_ch_mid_32_mid_12_shuffle1_2_width_32
  models: /home/jaewon/AIISP2024/experiments/NAFNetV3-baseline-enc3_ch_mid_32_mid_12_shuffle1_2_width_32/models
  training_states: /home/jaewon/AIISP2024/experiments/NAFNetV3-baseline-enc3_ch_mid_32_mid_12_shuffle1_2_width_32/training_states
  log: /home/jaewon/AIISP2024/experiments/NAFNetV3-baseline-enc3_ch_mid_32_mid_12_shuffle1_2_width_32
  visualization: /home/jaewon/AIISP2024/experiments/NAFNetV3-baseline-enc3_ch_mid_32_mid_12_shuffle1_2_width_32/visualization
train:
  optim_g:
    type: AdamW
    lr: 0.001
    weight_decay: 0.0
    betas:
    - 0.9
    - 0.9
  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: 1.0e-07
  total_iter: 200000
  warmup_iter: -1
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean
val:
  val_freq: 2000.0
  save_img: false
  use_image: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
logger:
  print_freq: 100
  save_checkpoint_freq: 2000.0
  use_tb_logger: true
  wandb:
    project: null
    resume_id: null
dist_params:
  backend: nccl
  port: 29500
is_train: true
dist: true
rank: 0
world_size: 2
